"""The public entry point, held to the output it publishes.

``examples/quickstart.py`` is what someone runs who has neither dataset, and
``examples/expected/`` is its committed output. A published expected output
that no longer matches the code is worse than none: it reads as evidence and
is a record of what the pipeline used to do. So the committed files are
regenerated by running the script, and these tests fail when they drift.

The example is also the only place the whole chain runs in one process --
window, judge, measure, assemble, split, score, export -- so a break anywhere
between the recording and the prediction shows up here even when every unit
test still passes.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

import pytest

numpy = pytest.importorskip("numpy")
pytest.importorskip("sklearn")
pytest.importorskip("scipy")

ROOT = Path(__file__).resolve().parent.parent
QUICKSTART = ROOT / "examples" / "quickstart.py"
EXPECTED = ROOT / "examples" / "expected"
REGENERATE = (
    "regenerate with: python examples/quickstart.py "
    "--write-trace examples/expected/prediction_trace.json "
    "> examples/expected/quickstart_output.txt"
)


@pytest.fixture(scope="module")
def produced(tmp_path_factory) -> tuple[str, dict]:
    """One run of the example, as a visitor would run it."""
    trace = tmp_path_factory.mktemp("trace") / "prediction_trace.json"
    finished = subprocess.run(
        [sys.executable, str(QUICKSTART), "--write-trace", str(trace)],
        capture_output=True,
        text=True,
        cwd=ROOT,
        timeout=600,
    )
    assert finished.returncode == 0, finished.stderr
    return finished.stdout, json.loads(trace.read_text())


def test_the_example_runs(produced):
    output, _trace = produced
    assert "[5/5] exporting one fold as traceable predictions" in output


def test_the_committed_output_still_matches(produced):
    output, _trace = produced
    committed = (EXPECTED / "quickstart_output.txt").read_text()
    assert output == committed, (
        f"the example's output has changed since it was published. {REGENERATE}"
    )


def test_the_committed_trace_still_matches(produced):
    _output, trace = produced
    committed = json.loads((EXPECTED / "prediction_trace.json").read_text())
    assert trace == committed, (
        f"the exported prediction chain has changed since it was published. {REGENERATE}"
    )


def test_every_published_prediction_names_what_produced_it(produced):
    _output, trace = produced
    assert trace["artifact"]["model_id"], "the artifact must name its own identity"
    assert trace["predictions"], "the trace is empty"
    for prediction in trace["predictions"]:
        assert prediction["prediction_id"].startswith("pred-")
        assert len(prediction["feature_ids"]) == 1
        assert prediction["feature_ids"][0].startswith("fvec-")
        # Four wrist sensors, so four windows. One would mean the row was
        # traceable to a single signal and silent about the other three.
        assert len(prediction["source_window_ids"]) == 4
        assert all(w.startswith("win-") for w in prediction["source_window_ids"])
        assert prediction["source_fact_ids"] == []


def test_the_published_window_is_the_one_that_was_measured(produced):
    """Sixty seconds, because that is what the example windows at.

    The export used to assume thirty regardless, so every peripheral prediction
    named an interval ending halfway through the signal it was computed from.
    """
    from datetime import datetime

    _output, trace = produced
    for prediction in trace["predictions"]:
        start = datetime.fromisoformat(prediction["window_start"])
        end = datetime.fromisoformat(prediction["window_end"])
        assert (end - start).total_seconds() == 60.0


def test_the_example_does_not_reach_for_cdfs(produced):
    """Nothing in the published demo touches the external provenance engine.

    The README says the library runs standalone. This is the claim tested
    rather than asserted: the example imports the pipeline, the evaluation and
    the export, and if any of them pulled CDFS in, the module would be loaded
    by the end of the run.
    """
    loaded = subprocess.run(
        [
            sys.executable,
            "-c",
            "import runpy, sys; "
            "sys.argv = ['quickstart']; "
            f"runpy.run_path({str(QUICKSTART)!r}, run_name='__main__'); "
            "print('CDFS_LOADED' if any("
            "m == 'cdfs' or m.startswith('cdfs.') for m in sys.modules) "
            "else 'CDFS_ABSENT', file=sys.stderr)",
        ],
        capture_output=True,
        text=True,
        cwd=ROOT,
        timeout=600,
    )
    assert loaded.returncode == 0, loaded.stderr
    assert "CDFS_ABSENT" in loaded.stderr, loaded.stderr


def test_the_scores_are_labelled_synthetic(produced):
    """A reader who sees only the output must not mistake it for a result.

    Printed at the top, beside the scores themselves, and again at the end,
    because terminal output gets screenshotted from the middle.
    """
    output, _trace = produced
    # Wrapped for the terminal, so compared with the wrapping collapsed.
    flowed = " ".join(output.split())
    assert "THE SCORES THIS PRINTS ARE MEANINGLESS" in flowed
    assert "describe the generator, not a result" in flowed
    assert "Synthetic data. The scores above are a property of this script." in flowed
